### ISSUE TITLE
Error executing autogen.sh in v24l

### ISSUE THREAD

**Issue by shawndfernandes** [groupgets/purethermal1-uvc-capture#1]
Description:
When executing autogen.sh, m4 directory is not created, and executing fails

CLI logs:
$ ./autogen.sh 
./autogen.sh: 7: ./autogen.sh: libtoolize: not found
aclocal: warning: couldn't open directory 'm4': No such file or directory
configure.ac:9: error: required directory ./m4 does not exist
configure.ac:13: error: installing 'm4/compile'; error while making link: No such file or directory
configure.ac:11: error: installing 'm4/install-sh'; error while making link: No such file or directory
configure.ac:11: error: installing 'm4/missing'; error while making link: No such file or directory
grab/Makefile.am: error: installing 'm4/depcomp'; error while making link: No such file or directory

Workaround:
Manually create m4 folder in v42l directory
$ ./autogen.sh 
./autogen.sh: 7: ./autogen.sh: libtoolize: not found
configure.ac:13: installing 'm4/compile'
configure.ac:11: installing 'm4/install-sh'
configure.ac:11: installing 'm4/missing'
grab/Makefile.am: installing 'm4/depcomp'

Reference:
https://github.com/hexchat/hexchat/issues/404

**Comment by kekiefer** [comment]
Thanks, added this directory to git.
