### ISSUE TITLE
Is there are C++ version for opencv-capture.py code?

### ISSUE THREAD

**Issue by spk921** [groupgets/purethermal1-uvc-capture#12]
Wondering that is there are example code with C++ of "opencv-capture.py" or "uvc-radiometry.py" ? 
I would like to combine with C++ application and could you point out some example code?

**Comment by kekiefer** [comment]
Such an example does not exist here. The sequence of calls should be the same. Reference the OpenCV documentation https://docs.opencv.org/3.4.6/index.html
