### ISSUE TITLE
Got error with Lepton3.5 

### ISSUE THREAD

**Issue by spk921** [groupgets/purethermal1-uvc-capture#13]
When I run the purethermal1-uvc-capture/v4l2/grab with Lepton3.5 I got following error even if I changed the resolution.

Libv4l didn't accept RGB24 format. Can't proceed.

**Comment by kekiefer** [comment]
Is this a permissions issue? Or a v4l2 driver bug? A lib4l2 change? When I run `v4l2-ctrl --list-formats-ext` on my PT board, I see BGR3 listed there.

**Comment by kekiefer** [comment]
Did you solve this problem?
