### ISSUE TITLE
_init_()missing 1 required positional argument: figure1''

### ISSUE THREAD

**Issue by Manuko99** [groupgets/purethermal1-uvc-capture#14]
I have followed the steps detailed in this project to run RecordIR_v18.3.py and PostProcessIR_v11.py.  The first file runs succesfully. However when I enter the command "sudo python 3 PostProcessIR_v11.py " to open this file from the console, but I got this error _init_()missing 1 required positional argument: figure11''. 

Please , can you help me how can I solve this issue?

Thank you so much.

**Comment by kekiefer** [comment]
To what steps are you referring? Those aren't scripts in this project.
