### ISSUE TITLE
uvcvideo error 28, No space left on device

### ISSUE THREAD

**Issue by etienenD** [groupgets/purethermal1-uvc-capture#18]
Hello everybody, 

I try to interface the Lepton3 with purthermal2 board with the ConnectCore6UL from Digi. 
I'm using Yocto 2.6-r1. When I use the pt1-v4l2-grab.c file I got the following error : 
libv4l2: error turning on stream: No space left on device
error 28, No space left on device

Is anybody had this error ? 

Thanks in advance for your response.

Etienne

**Comment by kekiefer** [comment]
disk full or read-only filesystem?

**Comment by etienenD** [comment]
I'm robot user so I supposed I have all right and I have enough space on the disk

**Comment by martinpeniak** [comment]
I have the same issue

**Comment by kekiefer** [comment]
See here https://github.com/groupgets/purethermal1-firmware/issues/24

**Comment by martinpeniak** [comment]
Thanks, that’s what I ended up doing yesterday because there was no other way. I’m now using 8-bit raw data and it’s even better than the rgb as now I can calculate temperatures
