### ISSUE TITLE
More than one screenshot

### ISSUE THREAD

**Issue by kamil321-rgb** [groupgets/purethermal1-uvc-capture#22]
Hi 
I need to take few "screnshots" into text file type using software from media foundation. I add `while (n != "q")` just after `pureThermal.PerformFFC();`. In while loop I get n value and its equal "q" quits. If not take another screenshot. It works ok, but after few minutes don't want to update data from frame any more. Any idea why?

**Comment by kekiefer** [comment]
Did you figure this out?
