### ISSUE TITLE
Lepton 3.5 + PT Mini not working

### ISSUE THREAD

**Issue by istranic** [groupgets/purethermal1-uvc-capture#25]
I'm having trouble getting my Lepton 3.5 to work with the Purethermal Mini. The same Lepton 3.5 works just fine with the Purethermal 2.

The issue is that the host computer recognizes the camera as 80x60, and the image appears scrambled when I display it via gstreamer or OpenCV. I have the same issue on a Raspberri Pi and Microsoft Surface.

Has anyone else had this issue?

**Comment by kekiefer** [comment]
Make sure the module is fully seated, then apply power.

**Comment by istranic** [comment]
Thanks, that worked.

**Comment by basavarajamogi** [comment]
I had same issue, I tried to put it properly but still it's not working
