### ISSUE TITLE
v4l2-ctl

### ISSUE THREAD

**Issue by victorkuys** [groupgets/purethermal1-uvc-capture#26]
I can load and modify my commands with v4l2-ctl. 
When I open a default application (like IR-capture), the default commands are reloaded, and my preferred changes are overwritten. 
How can I make sure this doesn't happen .... and where can I find these settings?

Thanks!

**Comment by kekiefer** [comment]
What is IR-capture? This sounds like a problem with that program changing settings on the camera.

**Comment by victorkuys** [comment]
Yes, I am trying to change the camera settings to enable other modes like the RAD emissivity. I had problems with the control id´s but i think there is a line of code that automatically changes the settings to default or something like that.
Thanks for the reply!
