### ISSUE TITLE
Lepton Radiometery wrong reading

### ISSUE THREAD

**Issue by Varat7v2** [groupgets/purethermal1-uvc-capture#28]
I am running `uvc-radiometry.py` on Ubuntu 18.04, video stream is working fine but the maximum and minimum temperature range are observed to be -312 degF and -316 degF. When I show the camera with something hot object, temperature reading is changing but I am confused with the range values. Is there anything I need to modify the calculations?

Also the video is gray, how can I make it same as that of `opencv-capture.py`?

Thank you.

**Comment by kekiefer** [comment]
Are you using a radiometric lepton (Lepton 2.5 or Lepton 3.5)? These are the only parts that support radiometric readings.

**Comment by Varat7v2** [comment]
@kekiefer  Thank you. I am using Lepton 3.0, so its not working.
