### ISSUE TITLE
Windows MediaFoundation Error - GetFrame File is Empty

### ISSUE THREAD

**Issue by RMichaelPickering** [groupgets/purethermal1-uvc-capture#32]
Tried the example on Windows 10 with Lepton 2.5 but the file "image_80x60_Y16.dat" contains only zeros, which is consistent with the reported minimum and maximum values being zero also. However, I'm sitting here in a room at a reasonable temperature and pointed the Lepton at myself -- I can assure you that the temperature here is well above zero Celsius!

**Comment by kekiefer** [comment]
Can you check if the camera module is seated all the way? Does it work on a different system or another OS?

**Comment by RMichaelPickering** [comment]
Thanks for your response, I believe we found this to be an issue of a missing DLL.
