### ISSUE TITLE
Get temperature from a specific area or spot 

### ISSUE THREAD

**Issue by BenjaminYeh83** [groupgets/purethermal1-uvc-capture#33]
Hello, I'm trying to integrate thermal data with my object detection function.
I have tried to modify the uvc-radiometry.py 
I was wondering what is the best way  to get the data from a specific area of spot instead of the whole image.

Thank you very much.

**Comment by kekiefer** [comment]
Each pixel contains temperature data. Pick the one you want, or average a few.

**Comment by BenjaminYeh83** [comment]
Thank you very much!
