### ISSUE TITLE
No video feed from opencv-capture.py

### ISSUE THREAD

**Issue by prat96** [groupgets/purethermal1-uvc-capture#4]
Hi all,

I have a Lepton 2.5 with Purethermal1. On executing opencv-capture.py, I dont get any video feed and the application force closes with a segmentation fault error.
Please advise!

![screenshot from 2018-05-24 11-22-38](https://user-images.githubusercontent.com/19527450/40466879-3100491a-5f45-11e8-8a2a-ba9783c59f35.png)

**Comment by kekiefer** [comment]
What firmware version is your purethermal 1 board?

**Comment by kekiefer** [comment]
Yes, OpenCV's video capture module does not support Y16.

If you want raw frame data, take a look at an an example using libuvc like uvc_radiometry.py

Also, current versions of firmware support both RGB and Y16 modes in the same firmware and stream more smoothly, it is recommended that you update (though not strictly required for the libuvc example I believe).

**Comment by prat96** [comment]
My bad, I should've checked! Will try the uvc_radiometry.py example.
Am unable to update the firmware on my PT1 as i've misplaced the JTAG adapter. 

Anyways, will start afresh on the new pair of PT2's ive ordered! :D

**Comment by prat96** [comment]
Hey @kekiefer, will the v4l2 examples work with Y16 firmware?
