### ISSUE TITLE
Radiometric script does not work: uvc_start_streamng failed: -2

### ISSUE THREAD

**Issue by maykef** [groupgets/purethermal1-uvc-capture#49]
Platform: NVIDIA TX2
Ubuntu 18.04 LTS
Python: 3.6.9
opencv: 4.5.0

Gstreamer examples run fine, as the opencv-capture.py.

Each time I try to run ./uvc-radiometry.py it gives me the following:

unsupported descriptor subtype VS_COLORFORMAT
unsupported descriptor subtype VS_COLORFORMAT
unsupported descriptor subtype VS_COLORFORMAT
unsupported descriptor subtype VS_COLORFORMAT
unsupported descriptor subtype VS_COLORFORMAT
device opened!
Version gpp: 3.3.26 dsp: 3.3.26
FLIR part #: 500-0771-01
FLIR serial #: '\xe4\xcf;\x01\x00\x00\x00\x00'
format: UYVY
  frame 160x120 @ 9fps
format: Y16 
  frame 160x120 @ 9fps
  frame 160x122 @ 9fps
format: Y8  
  frame 160x120 @ 9fps
format: RGBP
  frame 160x120 @ 9fps
format: }�6�
  frame 160x120 @ 9fps
uvc_start_streaming failed: -2

I know somebody reported this in the past and it was told this could be the libuvc library, but that is not enough to debug this. 

Thanks.

**Comment by Dineshkumar-code** [comment]
libuvc path may be wrong

**Comment by Dineshkumar-code** [comment]
kindly go to uvctypes.py to change the cdll.LoadLibrary("libuvc.so") to change path cdll.LoadLibrary("usr/local/lib/libuvc.so")

**Comment by maykef** [comment]
Hello @Dineshkumar-code 
Thanks for your pointer. I did change the path to "/usr/local/lib/libuvc.so" and it worked.
