### ISSUE TITLE
Problem uvc-radiometry.py

### ISSUE THREAD

**Issue by ignacio1988** [groupgets/purethermal1-uvc-capture#5]
Hi, I receive the following error and I do not understand why it happens. 
I updated the firmware to 1.0.0 [https://github.com/groupgets/purethermal1-firmware/releases/tag/1.0.0](url) and sometimes I can acquire images but I can not determine why. 
Any recommendation?

`device opened!
Version gpp: 0.0.0 dsp: 0.0.0
FLIR part #: 
FLIR serial #: '\x00\x00\x00\x00\x00\x00\x00\x00'
format: YUY2
  frame 640x480 @ 30fps
  frame 160x120 @ 30fps
  frame 176x144 @ 30fps
  frame 320x240 @ 30fps
  frame 352x288 @ 30fps
device does not support Y16
`

**Comment by kekiefer** [comment]
The frame sizes don't match what the PT1 firmware would be reporting, and all the version information is bogus. I would guess that a different camera on the system is being opened, do you have more than one UVC device connected?

**Comment by ignacio1988** [comment]
Hi, i connected a web camera with opencv at the same time wich purethermal  for adquisition in parrallel in the same code python.

**Comment by kekiefer** [comment]
OK... well have you pulled on that thread to determine if the simultaneous OpenCV is what is causing the conflicts?

**Comment by ignacio1988** [comment]
Hi, I discovered my problem. UVC did not find the purethermal because the USB VID/PID is was not the right one, I replaced the following line of code res = libuvc.uvc_find_device(ctx, byref(dev), 0, 0, 0) for this res = libuvc.uvc_find_device(ctx, byref(dev), 0x1e4e, 0x0100, 0).
Thanks very much.
REF: https://groups.google.com/forum/#!topic/flir-lepton/OLyUetrvMow

**Comment by kekiefer** [comment]
Good call, I have updated the examples with the change.
