### ISSUE TITLE
open VIDEOIO(AVFOUNDATION): raised unknown C++ exception!

### ISSUE THREAD

**Issue by mctosima** [groupgets/purethermal1-uvc-capture#50]
Hi, I've just trying the python code opencv-capture-2 on MacOS but it shows

<img width="810" alt="Screen Shot 2021-05-17 at 09 38 04" src="https://user-images.githubusercontent.com/22334778/118421432-cac2bc00-b6f3-11eb-9fe8-ede06c6c736a.png">

When I run this code on Linux, it works fine.
I'm using MacOS BigSur running on Macbook Pro 2020. OpenCV-Python Version 4.5.2.

Please help. I just learned more about Lepton

**Comment by carloscastellanos** [comment]
I am having this problem as well (Mac OS 10.15.6). Why is this closed? It does not appear to be resolved.

**Comment by rvegele** [comment]
same problem

**Comment by badgerhoneymoon** [comment]
same thing and the thread shouldn't be closed
