### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by gianluca-m** [groupgets/purethermal1-uvc-capture#59]
Hello

Since this repo does not include a license, we are actually legally not allowed to use it.
Source: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license

We are currently working on a non-commercial project which uses the Lepton FLIR camera to gather temperature data. We are students from the university "ETH Zurich" working on the project for one of our courses. 
For this we have used and modified parts of the contents of the following files:

- python/uvc-radiometry.py
- python/uvctypes.py

Are we allowed to do this? If yes, could you grant us a license or add a license to your repo?
And if not or you have another solution, please let us know.

Thanks

**Comment by kekiefer** [comment]
Consider the code hosted in this repo to be licensed under MIT. You are free to to as you propose.

You're correct that this is missing and should be explicit, so we'll get a license added.
