### ISSUE TITLE
Radiometry, libuvc and RPi3

### ISSUE THREAD

**Issue by agjunyent** [groupgets/purethermal1-uvc-capture#8]
Hi, 

I've trying to get the uvc-radiometry.py example to work on a Raspberry Pi 3 running Ubuntu Mate 16.04, but I'm not able to achieve it.

It starts fine, opens the device, report gpp, flir part and serial and all the formats, but it get stuck in the q.get(True, 500). It does never fill the QUEUE. I've tried changing the timeout, and it gets a timeout ALWAYS, does not matter the time.

Am I forgetting something?

**Comment by kekiefer** [comment]
Did you solve this problem?

**Comment by agjunyent** [comment]
Can be closed
